USE bet365;
DELETE FROM `bet365`.`T_M_MATCH_TEAM`;
DELETE FROM `bet365`.`T_M_BET_TGT_MATCH`;
DELETE FROM `bet365`.`T_M_MATCH_COUNTRY`;
DELETE FROM `bet365`.`T_M_MATCH_SEASON`;
DELETE FROM `bet365`.`T_M_EARLY_STAGE_BET_TYPE`;
DELETE FROM `bet365`.`T_M_GLOBAL_MATCH`;
DELETE FROM `bet365`.`T_M_MATCH_CATEGORY`;

DROP TABLE IF EXISTS `bet365`.`T_ORDER_DETAIL`;
DROP TABLE IF EXISTS `bet365`.`T_ORDER`;
DROP TABLE IF EXISTS `bet365`.`T_M_MATCH_TEAM`;
DROP TABLE IF EXISTS `bet365`.`T_M_BET_TGT_MATCH`;
DROP TABLE IF EXISTS `bet365`.`T_M_MATCH_COUNTRY`;
DROP TABLE IF EXISTS `bet365`.`T_M_MATCH_SEASON`;
DROP TABLE IF EXISTS `bet365`.`T_M_EARLY_STAGE_BET_TYPE`;
DROP TABLE IF EXISTS `bet365`.`T_M_GLOBAL_MATCH`;
DROP TABLE IF EXISTS `bet365`.`T_M_MATCH_CATEGORY`;