-- 英超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 1, 1, '曼彻斯特城', '曼城');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 1, 1, '曼彻斯特联', '曼联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 1, 1, '切尔西', '切尔西');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 1, 1, '阿森纳', '阿森纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 1, 1, '伯恩利', '伯恩利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 1, 1, '利物浦', '利物浦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 1, 1, '托特纳姆热刺', '热刺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 1, 1, '莱切斯特城', '莱切城');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 1, 1, '沃特福德', '沃特福');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 1, 1, '埃弗顿', '埃弗顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 1, 1, '哈德斯菲尔德', '哈德斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 1, 1, '南安普敦', '南安普');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 1, 1, '布赖顿', '布赖顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 1, 1, '水晶宫', '水晶宫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 1, 1, '西汉姆联', '西汉姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 1, 1, '伯恩茅斯', '伯恩茅');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 1, 1, '斯托克城', '斯托克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 1, 1, '纽卡斯尔联', '纽卡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 1, 1, '西布罗姆维奇', '西布罗');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 1, 1, '斯旺西', '斯旺西');

-- 英冠
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 2, 1, '狼队', '狼队');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 2, 1, '加的夫城', '加的夫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 2, 1, '布里斯托尔城', '布里斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 2, 1, '德比郡', '德比郡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 2, 1, '阿斯顿维拉', '维拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 2, 1, '谢菲尔德联', '谢菲联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 2, 1, '利兹联', '利兹');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 2, 1, '伊普斯维奇', '伊普斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 2, 1, '普雷斯顿', '普雷斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 2, 1, '米德尔斯堡', '米德尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 2, 1, '诺丁汉森林', '诺丁汉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 2, 1, '富勒姆', '富勒姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 2, 1, '布伦特福德', '布伦特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 2, 1, '雷丁', '雷丁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 2, 1, '谢菲尔德星期三', '谢周三');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 2, 1, '诺维奇', '诺维奇');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 2, 1, '米尔沃尔', '米尔沃');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 2, 1, '女王公园巡游者', '巡游者');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 2, 1, '赫尔城', '赫尔城');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 2, 1, '巴恩斯利', '巴恩斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(21, 2, 1, '桑德兰', '桑德兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(22, 2, 1, '伯顿', '伯顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(23, 2, 1, '博尔顿', '博尔顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(24, 2, 1, '伯明翰', '伯明翰');

-- 英甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 3, 1, '维冈竞技', '维冈');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 3, 1, '什鲁斯伯里', '什鲁斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 3, 1, '布莱克本', '布莱克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 3, 1, '布拉德福德', '布拉德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 3, 1, '斯肯索普', '斯肯索');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 3, 1, '查尔顿', '查尔顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 3, 1, '朴茨茅斯', '朴茨茅');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 3, 1, '牛津联', '牛津联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 3, 1, '罗瑟汉姆', '罗瑟汉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 3, 1, '彼得堡联', '彼得堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 3, 1, '沃尔索尔', '沃尔索');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 3, 1, '南安联', '南安联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 3, 1, '福利特伍德', '福利特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 3, 1, '布莱克浦', '布莱浦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 3, 1, '奥德汉姆', '奥德汉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 3, 1, '布里斯托尔流浪', '布流浪');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 3, 1, '米尔顿凯恩斯', '米尔顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 3, 1, '唐卡斯特', '唐卡斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 3, 1, '吉灵汉姆', '吉灵汉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 3, 1, '北安普敦', '北安普');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(21, 3, 1, '罗奇代尔', '罗奇代');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(22, 3, 1, '普利茅斯', '普利茅');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(23, 3, 1, 'AFC温布尔登', '温布尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(24, 3, 1, '贝里', '贝里');

-- 英乙
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 4, 1, '卢顿', '卢顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 4, 1, '诺茨郡', '诺茨郡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 4, 1, '埃克赛特城', '埃克赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 4, 1, '韦康比流浪者', '韦康比');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 4, 1, '阿克宁顿', '阿克灵');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 4, 1, '林肯城', '林肯城');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 4, 1, '考文垂', '考文垂');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 4, 1, '科尔切斯特联', '科尔切');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 4, 1, '纽波特郡', '纽波特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 4, 1, '曼斯菲尔德', '曼斯菲');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 4, 1, '格林斯比', '格林斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 4, 1, '斯文登', '斯文登');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 4, 1, '剑桥联', '剑桥联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 4, 1, '卡利斯尔联', '卡利斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 4, 1, '切尔滕汉姆', '切尔滕');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 4, 1, '斯蒂文尼奇', '斯蒂文');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 4, 1, '克劳利', '克劳利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 4, 1, '维尔港', '维尔港');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 4, 1, '克鲁', '克鲁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 4, 1, '莫克姆', '莫克姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(21, 4, 1, '约维尔', '约维尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(22, 4, 1, '巴尼特', '巴尼特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(23, 4, 1, '切斯特菲尔德', '切斯特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(24, 4, 1, '格兰森林流浪', '格兰森');

-- 西甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 20, 1, '巴塞罗那', '巴萨');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 20, 1, '马德里竞技', '马竞技');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 20, 1, '巴伦西亚', '巴伦西');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 20, 1, '皇家马德里', '皇马');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 20, 1, '塞维利亚', '塞维利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 20, 1, '比利亚雷亚尔', '比利亚');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 20, 1, '埃瓦尔', '埃瓦尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 20, 1, '赫塔费', '赫塔费');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 20, 1, '皇家社会', '社会');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 20, 1, '莱加内斯', '莱加内');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 20, 1, '赫罗纳', '赫罗纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 20, 1, '维戈塞尔塔', '塞尔塔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 20, 1, '毕尔巴鄂竞技', '毕尔巴');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 20, 1, '皇家贝蒂斯', '贝蒂斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 20, 1, '莱万特', '莱万特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 20, 1, '西班牙人', '西牙人');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 20, 1, '拉科鲁尼亚', '拉科鲁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 20, 1, '阿拉维斯', '阿拉维');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 20, 1, '马拉加', '马拉加');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 20, 1, '拉斯帕尔马斯', '拉斯帕');

-- 意甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 40, 1, '那不勒斯', '那不勒');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 40, 1, '国际米兰', '国米');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 40, 1, '尤文图斯', '尤文');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 40, 1, '罗马', '罗马');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 40, 1, '拉齐奥', '拉齐奥');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 40, 1, '桑普多利亚', '桑普多');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 40, 1, 'AC米兰', 'AC米兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 40, 1, '亚特兰大', '亚特兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 40, 1, '都灵', '都灵');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 40, 1, '佛罗伦萨', '佛罗伦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 40, 1, '乌迪内斯', '乌迪内');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 40, 1, '博洛尼亚', '博洛尼');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 40, 1, '切沃', '切沃');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 40, 1, '卡利亚里', '卡利亚');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 40, 1, '萨索洛', '萨索洛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 40, 1, '热那亚', '热那亚');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 40, 1, '克罗托内', '克罗托');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 40, 1, '士柏', '士柏');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 40, 1, '维罗纳', '维罗纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 40, 1, '贝内文托', '贝内文');

-- 意乙
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 41, 1, '巴勒莫', '巴勒莫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 41, 1, '巴里', '巴里');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 41, 1, '帕尔马', '帕尔马');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 41, 1, '弗洛西诺内', '弗洛西');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 41, 1, '恩波利', '恩波利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 41, 1, '希塔德拉', '希塔德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 41, 1, '科雷蒙尼斯', '科雷蒙');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 41, 1, '威尼斯', '威尼斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 41, 1, '萨勒尼塔纳', '萨勒尼');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 41, 1, '斯佩齐亚', '斯佩齐');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 41, 1, '卡尔皮', '卡皮');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 41, 1, '佩鲁贾', '佩鲁贾');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 41, 1, '诺瓦拉', '诺瓦拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 41, 1, '阿韦利诺', '阿韦利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 41, 1, '切塞纳', '切塞纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 41, 1, '布雷西亚', '布雷西');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 41, 1, '恩特拉', '恩特拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 41, 1, '佩斯卡拉', '佩斯卡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 41, 1, '霍治亚', '霍治亚');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 41, 1, '特拉纳', '特拉纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(21, 41, 1, '韦尔切利', '韦尔切');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(22, 41, 1, '阿斯科利', '阿斯科');

-- 德甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 60, 1, '拜仁慕尼黑', '拜仁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 60, 1, '沙尔克04', '沙尔克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 60, 1, '多特蒙德', '多特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 60, 1, '莱比锡红牛', '莱比锡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 60, 1, '门兴格拉德巴赫', '门兴');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 60, 1, '勒沃库森', '勒沃');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 60, 1, '霍芬海姆', '霍芬');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 60, 1, '法兰克福', '法兰克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 60, 1, '奥格斯堡', '奥格斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 60, 1, '汉诺威96', '汉诺威');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 60, 1, '柏林赫塔', '赫塔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 60, 1, '沃尔夫斯堡', '沃尔夫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 60, 1, '弗赖堡', '弗赖堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 60, 1, '斯图加特', '斯图加');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 60, 1, '美因茨', '美因茨');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 60, 1, '云达不来梅', '不来梅');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 60, 1, '汉堡', '汉堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 60, 1, '科隆', '科隆');

-- 德乙
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 61, 1, '杜塞尔多夫', '杜塞尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 61, 1, '基尔高士丁', '基尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 61, 1, '纽伦堡', '纽伦堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 61, 1, '因戈尔施塔特', '因戈尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 61, 1, '桑德豪森', '桑德豪');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 61, 1, '柏林联合', '柏林联');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 61, 1, '杜伊斯堡', '杜伊斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 61, 1, '雷根斯堡', '雷根堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 61, 1, '比勒费尔德', '比勒费');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 61, 1, '德累斯顿', '德累斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 61, 1, '波鸿', '波鸿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 61, 1, '奥厄', '奥厄');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 61, 1, '不伦瑞克', '不伦瑞');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 61, 1, '海登海姆', '海登');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 61, 1, '圣保利', '圣保利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 61, 1, '达姆施塔特', '达姆施');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 61, 1, '菲尔特', '菲尔特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 61, 1, '凯泽斯劳滕', '凯泽');

-- 法甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 80, 1, '巴黎圣日尔曼', '日尔曼');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 80, 1, '摩纳哥', '摩纳哥');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 80, 1, '里昂', '里昂');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 80, 1, '马赛', '马赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 80, 1, '南特', '南特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 80, 1, '雷恩', '雷恩');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 80, 1, '第戎', '第戎');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 80, 1, '斯特拉斯堡', '斯特堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 80, 1, '卡昂', '卡昂');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 80, 1, '蒙彼利埃', '蒙彼利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 80, 1, '甘冈', '甘冈');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 80, 1, '尼斯', '尼斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 80, 1, '亚眠', '亚眠');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 80, 1, '特鲁瓦', '特鲁瓦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 80, 1, '波尔多', '波尔多');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 80, 1, '圣埃蒂安', '埃蒂安');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 80, 1, '图卢兹', '图卢兹');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 80, 1, '里尔', '里尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 80, 1, '昂热', '昂热');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 80, 1, '梅斯', '梅斯');

-- 法乙
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 81, 1, '兰斯', '兰斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 81, 1, '尼姆', '尼姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 81, 1, '阿雅克肖', '阿雅克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 81, 1, '勒阿弗尔', '阿弗尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 81, 1, '布雷斯特', '布雷斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 81, 1, '巴黎FC', '巴黎FC');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 81, 1, '洛里昂', '洛里昂');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 81, 1, '索肖', '索肖');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 81, 1, '克莱蒙', '克莱蒙');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 81, 1, '沙托鲁', '沙托鲁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 81, 1, '尼奥尔', '尼奥尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 81, 1, '瓦朗谢纳', '瓦朗谢');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 81, 1, '奥尔良', '奥尔良');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 81, 1, '阿雅克肖GFCO', '阿雅GF');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 81, 1, '南锡', '南锡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 81, 1, '欧塞尔', '欧塞尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 81, 1, '朗斯', '朗斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 81, 1, '布尔格', '布尔格');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(19, 81, 1, '奎维利鲁昂', '奎维利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(20, 81, 1, '图尔', '图尔');

-- 丹超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 110, 1, '中日德兰', '中日兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 110, 1, '布隆德比', '布隆德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 110, 1, '北西兰', '北西兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 110, 1, '霍布罗', '霍布罗');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 110, 1, '霍森斯', '霍森斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 110, 1, '哥本哈根', '哥本哈');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 110, 1, '奥尔堡', '奥尔堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 110, 1, '欧登塞', '欧登塞');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 110, 1, '桑德捷斯基', '桑德捷');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 110, 1, '施克堡', '施克堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 110, 1, '奥胡斯', '奥胡斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 110, 1, '利恩比', '利恩比');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 110, 1, '比利希尔星格', '比利希');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 110, 1, '兰纳斯', '兰纳斯');

-- 俄超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 120, 1, '莫斯科火车头', '莫火车');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 120, 1, '圣彼得堡泽尼特', '泽尼特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 120, 1, '莫斯科斯巴达', '莫斯巴');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 120, 1, '克拉斯诺达尔', '克拉斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 120, 1, '莫斯科中央陆军', '莫陆军');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 120, 1, '乌法', '乌法');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 120, 1, '格罗兹尼捷列克', '格罗兹');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 120, 1, '乌拉尔', '乌拉尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 120, 1, '罗斯托夫', '罗斯托');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 120, 1, '图拉', '图拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 120, 1, '喀山红宝石', '喀山');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 120, 1, '莫斯科迪纳摩', '莫迪纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 120, 1, '阿姆卡尔', '阿姆卡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 120, 1, '图斯诺', '图斯诺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 120, 1, '安郅马哈奇卡拉', '安郅');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 120, 1, 'SKA恩纳吉亚', 'SKA恩');

-- 荷甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 130, 1, 'PSV埃因霍温', '埃因霍');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 130, 1, '阿贾克斯', '阿贾克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 130, 1, '阿尔克马尔', '阿尔克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 130, 1, '兹沃勒', '兹沃勒');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 130, 1, '费耶诺德', '费耶诺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 130, 1, '乌德勒支', '乌德勒');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 130, 1, '维迪斯', '维迪斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 130, 1, '海伦芬', '海伦芬');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 130, 1, '海牙', '海牙');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 130, 1, '赫拉克勒斯', '赫拉克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 130, 1, '芬洛', '芬洛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 130, 1, '格罗宁根', '格罗宁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 130, 1, 'SBV精英', '精英');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 130, 1, '威廉二世', '威廉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 130, 1, '特温特', '特温特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 130, 1, '布雷达', '布雷达');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 130, 1, '罗达JC', '罗达JC');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 130, 1, '鹿特丹斯巴达', '鹿特丹');

-- 捷克甲
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 140, 1, '比尔森', '比尔森');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 140, 1, '布拉格斯拉维亚', '斯拉维');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 140, 1, '奥洛莫茨', '奥洛莫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 140, 1, '利贝雷茨', '利贝雷');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 140, 1, '布拉格斯巴达', '布拉格');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 140, 1, '特普利斯', '特普利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 140, 1, '波希米亚1905', '波1905');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 140, 1, '亚布洛内茨', '亚布洛内');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 140, 1, '兹林', '兹林');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 140, 1, '杜库拉', '杜库拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 140, 1, '博雷斯拉夫', '博莱斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 140, 1, '布尔诺', '布尔诺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 140, 1, '卡维纳', '卡维纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 140, 1, '斯洛瓦科', '斯洛瓦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 140, 1, '奥斯特拉瓦', '奥斯特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 140, 1, '伊希拉瓦', '伊希拉');


-- 挪超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 160, 1, '罗森博格', '罗森博');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 160, 1, '莫尔德', '莫尔德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 160, 1, '萨尔普斯堡', '萨堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 160, 1, '斯特罗姆加斯特', '斯特罗');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 160, 1, '布兰', '布兰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 160, 1, '奥德', '奥德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 160, 1, '克里斯蒂安松', '克里斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 160, 1, '瓦勒伦加', '瓦勒伦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 160, 1, '斯塔贝克', '斯塔贝');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 160, 1, '海于格松', '海于松');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 160, 1, '特罗姆瑟', '特罗姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 160, 1, '利勒斯特罗姆', '利勒斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 160, 1, '桑纳菲尤尔', '桑德');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 160, 1, '松达尔', '松达尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 160, 1, '奥勒松', '奥勒松');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 160, 1, '维京', '维京');

-- 葡超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 170, 1, '波尔图', '波尔图');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 170, 1, '里斯本竞技', '里斯本');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 170, 1, '本菲卡', '本菲卡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 170, 1, '布拉加', '布拉加');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 170, 1, '马里迪莫', '马里迪');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 170, 1, '里奥阿维', '里奥阿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 170, 1, '吉马良斯', '吉马良');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 170, 1, '博阿维斯塔', '博维斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 170, 1, '查维斯', '查维斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 170, 1, '比兰尼塞斯', '比兰尼');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 170, 1, '波尔蒂芒尼斯', '波尔蒂');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 170, 1, '通德拉', '通德拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 170, 1, '艾维斯', '艾维斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 170, 1, '费雷拉', '费雷拉');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 170, 1, '菲伦斯', '菲伦斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 170, 1, '埃斯托里尔', '埃斯托');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 170, 1, '塞图巴尔', '塞图巴');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 170, 1, '摩雷伦斯', '摩雷伦斯');

-- 瑞超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 180, 1, '马尔默', '马尔默');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 180, 1, 'AIK索尔纳', '索尔纳');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 180, 1, '佐加顿斯', '佐加顿');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 180, 1, '赫根', '赫根');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 180, 1, '厄斯特松德', '厄斯松');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 180, 1, '北雪平', '北雪平');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 180, 1, '天狼星', '天狼星');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 180, 1, '埃尔夫斯堡', '埃尔夫');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 180, 1, '哈马比', '哈马比');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 180, 1, 'IFK哥德堡', '哥德堡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 180, 1, '厄勒布鲁', '厄勒布');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 180, 1, '卡尔马', '卡尔马');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 180, 1, '松兹瓦尔', '松兹瓦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 180, 1, '延雪平', '延雪平');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 180, 1, '哈尔姆斯塔德', '哈尔姆');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 180, 1, '埃斯基尔斯蒂纳', '埃斯基');

-- 瑞士超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 190, 1, '年轻人', '年轻人');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 190, 1, '巴塞尔', '巴塞尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 190, 1, '苏黎世', '苏黎世');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 190, 1, '圣加仑', '圣加仑');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 190, 1, '草蜢', '草蜢');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 190, 1, '洛桑', '洛桑');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 190, 1, '卢加诺', '卢加诺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 190, 1, '图恩', '图恩');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 190, 1, '卢塞恩', '卢塞恩');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 190, 1, '锡永', '锡永');

-- 苏超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 200, 1, '凯尔特人', '凯尔特');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 200, 1, '阿伯丁', '阿伯丁');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 200, 1, '格拉斯哥流浪者', '流浪者');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 200, 1, '希伯尼安', '希伯尼');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 200, 1, '哈茨', '哈茨');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 200, 1, '圣约翰斯通', '圣约翰');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 200, 1, '马瑟韦尔', '马瑟韦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 200, 1, '基尔马诺克', '基马诺');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 200, 1, '汉密尔顿', '哈密尔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 200, 1, '邓迪FC', '邓迪');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 200, 1, '罗斯郡', '罗斯郡');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 200, 1, '帕尔蒂克', '帕尔蒂');

-- 土超
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(1, 210, 1, '伊斯坦布尔', '伊斯坦');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(2, 210, 1, '加拉塔萨雷', '加拉塔');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(3, 210, 1, '开塞利体育', '开塞利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(4, 210, 1, '费内巴切', '费内巴');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(5, 210, 1, '特拉布宗体育', '特拉布');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(6, 210, 1, '贝西克塔斯', '贝西克');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(7, 210, 1, '哥兹塔比', '哥兹塔比');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(8, 210, 1, '布尔萨体育', '布尔萨');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(9, 210, 1, '锡瓦斯体育', '锡瓦斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(10, 210, 1, '卡斯帕萨', '卡斯帕');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(11, 210, 1, '阿卡沙', '阿卡沙');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(12, 210, 1, '阿兰亚斯堡', '阿兰亚斯');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(13, 210, 1, '马拉耶士邦', '马拉耶');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(14, 210, 1, '奥斯曼体育', '奥斯体');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(15, 210, 1, '科尼亚体育', '科尼亚');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(16, 210, 1, '安塔利亚体育', '安塔利');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(17, 210, 1, '根克勒比利吉', '根克勒');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`) VALUES(18, 210, 1, '卡拉比克体育', '卡拉比');

-- 世界杯
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(1, 1000, 3, '俄罗斯', '俄罗斯', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(2, 1000, 3, '乌拉圭', '乌拉圭', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(3, 1000, 3, '沙特', '沙特', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(4, 1000, 3, '埃及', '埃及', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(5, 1000, 3, '西班牙', '西班牙', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(6, 1000, 3, '葡萄牙', '葡萄牙', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(7, 1000, 3, '伊朗', '伊朗', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(8, 1000, 3, '摩洛哥', '摩洛哥', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(9, 1000, 3, '丹麦', '丹麦', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(10, 1000, 3, '法国', '法国', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(11, 1000, 3, '澳大利亚', '澳大利亚', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(12, 1000, 3, '秘鲁', '秘鲁', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(13, 1000, 3, '阿根廷', '阿根廷', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(14, 1000, 3, '尼日利亚', '尼日利亚', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(15, 1000, 3, '克罗地亚', '克罗地亚', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(16, 1000, 3, '冰岛', '冰岛', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(17, 1000, 3, '塞尔维亚', '塞尔维亚', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(18, 1000, 3, '哥斯达黎加', '哥斯达黎加', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(19, 1000, 3, '巴西', '巴西', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(20, 1000, 3, '瑞士', '瑞士', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(21, 1000, 3, '德国', '德国', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(22, 1000, 3, '墨西哥', '墨西哥', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(23, 1000, 3, '韩国', '韩国', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(24, 1000, 3, '瑞典', '瑞典', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(25, 1000, 3, '英格兰', '英格兰', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(26, 1000, 3, '比利时', '比利时', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(27, 1000, 3, '突尼斯', '突尼斯', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(28, 1000, 3, '巴拿马', '巴拿马', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(29, 1000, 3, '哥伦比亚', '哥伦比亚', 'H', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(30, 1000, 3, '日本', '日本', 'H', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(31, 1000, 3, '塞内加尔', '塞内加尔', 'H', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(32, 1000, 3, '波兰', '波兰', 'H', '', '32强(小组赛)');

-- 欧冠
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(1, 2000, 1, '曼彻斯特联', '', 'A', '塞维利亚', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(2, 2000, 1, '巴塞尔', '', 'A', '曼彻斯特城', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(3, 2000, 1, '莫斯科中央陆军', '', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(4, 2000, 1, '本菲卡', '', 'A', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(5, 2000, 1, '巴黎圣日尔曼', '', 'B', '皇家马德里', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(6, 2000, 1, '拜仁慕尼黑', '', 'B', '贝西克塔斯', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(7, 2000, 1, '凯尔特人', '', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(8, 2000, 1, '安德莱赫特', '', 'B', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(9, 2000, 1, '罗马', '', 'C', '顿涅茨克矿工', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(10, 2000, 1, '切尔西', '', 'C', '巴塞罗那', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(11, 2000, 1, '马德里竞技', '', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(12, 2000, 1, '卡拉巴赫', '', 'C', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(13, 2000, 1, '巴塞罗那', '', 'D', '切尔西', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(14, 2000, 1, '尤文图斯', '', 'D', '托特纳姆热刺', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(15, 2000, 1, '里斯本竞技', '', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(16, 2000, 1, '奥林匹亚科斯', '', 'D', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(17, 2000, 1, '利物浦', '', 'E', '波尔图', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(18, 2000, 1, '塞维利亚', '', 'E', '曼彻斯特联', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(19, 2000, 1, '莫斯科斯巴达', '', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(20, 2000, 1, '马里博尔', '', 'E', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(21, 2000, 1, '曼彻斯特城', '', 'F', '巴塞尔', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(22, 2000, 1, '顿涅茨克矿工', '', 'F', '罗马', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(23, 2000, 1, '那不勒斯', '', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(24, 2000, 1, '费耶诺德', '', 'F', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(25, 2000, 1, '贝西克塔斯', '', 'G', '拜仁慕尼黑', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(26, 2000, 1, '波尔图', '', 'G', '利物浦', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(27, 2000, 1, '莱比锡红牛', '', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(28, 2000, 1, '摩纳哥', '', 'G', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(29, 2000, 1, '托特纳姆热刺', '', 'H', '尤文图斯', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(30, 2000, 1, '皇家马德里', '', 'H', '巴黎圣日尔曼', '16强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(31, 2000, 1, '多特蒙德', '', 'H', '', '32强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(32, 2000, 1, '希腊人竞技', '', 'H', '', '32强(小组赛)');

-- 欧联
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(1, 2001, 1, '比利亚雷亚尔', '', 'A', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(2, 2001, 1, '阿斯塔纳', '', 'A', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(3, 2001, 1, '布拉格斯拉维亚', '', 'A', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(4, 2001, 1, '特拉维夫马卡比', '', 'A', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(5, 2001, 1, '基辅迪纳摩', '', 'B', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(6, 2001, 1, '贝尔格莱德游击', '', 'B', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(7, 2001, 1, '年轻人', '', 'B', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(8, 2001, 1, '科尔察', '', 'B', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(9, 2001, 1, '布拉加', '', 'C', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(10, 2001, 1, '卢多戈雷茨', '', 'C', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(11, 2001, 1, '伊斯坦布尔', '', 'C', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(12, 2001, 1, '霍芬海姆', '', 'C', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(13, 2001, 1, 'AC米兰', '', 'D', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(14, 2001, 1, '雅典AEK', '', 'D', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(15, 2001, 1, '里耶卡', '', 'D', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(16, 2001, 1, '奥地利维也纳', '', 'D', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(17, 2001, 1, '亚特兰大', '', 'E', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(18, 2001, 1, '里昂', '', 'E', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(19, 2001, 1, '埃弗顿', '', 'E', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(20, 2001, 1, '阿波隆利马索尔', '', 'E', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(21, 2001, 1, '莫斯科火车头', '', 'F', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(22, 2001, 1, '哥本哈根', '', 'F', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(23, 2001, 1, '谢里夫', '', 'F', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(24, 2001, 1, '兹林', '', 'F', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(25, 2001, 1, '比尔森', '', 'G', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(26, 2001, 1, '布加勒斯特星', '', 'G', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(27, 2001, 1, '卢加诺', '', 'G', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(28, 2001, 1, '贝尔谢巴夏普尔', '', 'G', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(29, 2001, 1, '阿森纳', '', 'H', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(30, 2001, 1, '贝尔格莱德红星', '', 'H', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(31, 2001, 1, '科隆', '', 'H', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(32, 2001, 1, '巴特', '', 'H', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(33, 2001, 1, '萨尔茨堡', '', 'I', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(34, 2001, 1, '马赛', '', 'I', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(35, 2001, 1, '科尼亚体育', '', 'I', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(36, 2001, 1, '吉马良斯', '', 'I', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(37, 2001, 1, '毕尔巴鄂竞技', '', 'J', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(38, 2001, 1, '厄斯特松德', '', 'J', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(39, 2001, 1, '卢甘斯克黎明', '', 'J', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(40, 2001, 1, '柏林赫塔', '', 'J', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(41, 2001, 1, '拉齐奥', '', 'K', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(42, 2001, 1, '尼斯', '', 'K', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(43, 2001, 1, '聚尔特瓦雷赫姆', '', 'K', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(44, 2001, 1, '维迪斯', '', 'K', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(45, 2001, 1, '圣彼得堡泽尼特', '', 'L', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(46, 2001, 1, '皇家社会', '', 'L', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(47, 2001, 1, '罗森博格', '', 'L', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(48, 2001, 1, '瓦尔达尔', '', 'L', '', '48强(小组赛)');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(49, 2001, 1, '莫斯科中央陆军', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(50, 2001, 1, '凯尔特人', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(51, 2001, 1, '马德里竞技', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(52, 2001, 1, '里斯本竞技', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(53, 2001, 1, '莫斯科斯巴达', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(54, 2001, 1, '那不勒斯', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(55, 2001, 1, '莱比锡红牛', '', '欧冠小组第3', '', '32强');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(56, 2001, 1, '多特蒙德', '', '欧冠小组第3', '', '32强');

-- NBA
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(1, 10000, 1, '华盛顿奇才', '奇才', '东南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(2, 10000, 1, '迈阿密热火', '热火', '东南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(3, 10000, 1, '奥兰多魔术', '魔术', '东南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(4, 10000, 1, '夏洛特黄蜂', '黄蜂', '东南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(5, 10000, 1, '亚特兰大老鹰', '老鹰', '东南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(6, 10000, 1, '波士顿凯尔特人', '凯尔特人', '大西洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(7, 10000, 1, '多伦多猛龙', '猛龙', '大西洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(8, 10000, 1, '纽约尼克斯', '尼克斯', '大西洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(9, 10000, 1, '费城76人', '76人', '大西洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(10, 10000, 1, '布鲁克林篮网队', '篮网', '大西洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(11, 10000, 1, '克里夫兰骑士', '骑士', '中央赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(12, 10000, 1, '底特律活塞', '活塞', '中央赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(13, 10000, 1, '印第安纳步行者', '步行者', '中央赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(14, 10000, 1, '密尔沃基雄鹿', '雄鹿', '中央赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(15, 10000, 1, '芝加哥公牛', '公牛', '中央赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(16, 10000, 1, '休斯顿火箭', '火箭', '西南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(17, 10000, 1, '圣安东尼奥马刺', '马刺', '西南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(18, 10000, 1, '新奥尔良鹈鹕', '鹈鹕', '西南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(19, 10000, 1, '孟菲斯灰熊', '灰熊', '西南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(20, 10000, 1, '达拉斯小牛', '小牛', '西南赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(21, 10000, 1, '明尼苏达森林狼', '森林狼', '西北赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(22, 10000, 1, '丹佛掘金', '掘金', '西北赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(23, 10000, 1, '波特兰开拓者', '开拓者', '西北赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(24, 10000, 1, '俄克拉荷马雷霆', '雷霆', '西北赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(25, 10000, 1, '犹他爵士', '爵士', '西北赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(26, 10000, 1, '金州勇士', '勇士', '太平洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(27, 10000, 1, '洛杉矶快船', '快船', '太平洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(28, 10000, 1, '洛杉矶湖人', '湖人', '太平洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(29, 10000, 1, '菲尼克斯太阳', '太阳', '太平洋赛区', '', '常规赛');
INSERT INTO `bet365`.`t_m_match_team`(`team_id`, `match_id`, `match_ssn_id`, `team_name`, `team_short_name`, `match_group`, `knkt_match_rival`, `team_standing`) VALUES(30, 10000, 1, '萨克拉门托国王', '国王', '太平洋赛区', '', '常规赛');


