INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(1, '英格兰超级联赛', '英超', 1, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(2, '英格兰冠军联赛', '英冠', 1, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(3, '英格兰甲级联赛', '英甲', 1, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(4, '英格兰乙级联赛', '英乙', 1, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(20, '西班牙甲级联赛', '西甲', 2, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(40, '意大利甲级联赛', '意甲', 3, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(41, '意大利乙级联赛', '意乙', 3, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(60, '德国甲级联赛', '意甲', 4, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(61, '德国乙级联赛', '意乙', 4, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(80, '法国甲级联赛', '意甲', 5, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(81, '法国乙级联赛', '意乙', 5, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(100, '比利时甲级联赛', '比甲', 6, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(110, '丹麦超级联赛', '丹超', 7, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(120, '俄罗斯超级联赛', '俄超', 8, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(130, '荷兰甲级联赛', '荷甲', 9, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(140, '捷克甲级联赛', '捷克甲', 10, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(150, '克罗地亚甲级联赛', '克罗甲', 11, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(160, '挪威超级联赛', '挪超', 12, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(170, '葡萄牙超级联赛', '葡超', 13, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(180, '瑞典超级联赛', '瑞超', 14, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(190, '瑞士超级联赛', '瑞士超', 15, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(200, '苏格兰超级联赛', '苏超', 16, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(210, '土耳其超级联赛', '土超', 17, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_category`) VALUES(220, '希腊超级联赛', '希腊超', 18, 1, 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(1000, '世界杯', '世界杯', 100, 3, '32强', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(2000, '欧洲冠军联赛', '欧冠', 200, 1, '16强', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(2001, '欧洲联赛', '欧联', 200, 1, '32强', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(3000, '南美解放者杯赛', '解放者杯', 300, 2, '冠军', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(3001, '南美俱乐部杯赛', '南俱杯', 300, 2, '冠军', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(4000, '亚洲冠军联赛', '亚冠', 400, 2, '冠军', 1);
INSERT INTO `bet365`.`t_m_bet_tgt_match`(`match_id`, `match_name`, `match_short_name`, `match_belongs_in_cy_id`, `match_ssn_id`, `match_crrt_stage`, `match_category`) VALUES(10000, '美国职业足球联赛', 'NBA', 19, 1, '常规赛', 2);