package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TMBetTgtMatch generated by hbm2java
 */
@Entity
@Table(name="t_m_bet_tgt_match")
public class TMBetTgtMatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1398084954934213006L;
	@Id
	@Column(name="match_id")
	private int matchId;
	
	@OneToOne
	@JoinColumn(name="match_category")
	private TMMatchCategory tMMatchCategory;
	
	@OneToOne
	@JoinColumn(name="match_belongs_in_cy_id")
	private TMMatchCountry tMMatchCountry;
	
	@OneToOne
	@JoinColumn(name="match_ssn_id")
	private TMMatchSeason tMMatchSeason;
	
	@Column(name = "match_name")
	private String matchName;
	
	@Column(name = "match_short_name")
	private String matchShortName;
	
	@Column(name = "match_crrt_stage")
	private String matchCrrtStage;

	public TMBetTgtMatch() {
	}

	public TMBetTgtMatch(int matchId) {
		super();
		this.matchId = matchId;
	}

	public TMBetTgtMatch(int matchId, TMMatchCategory tMMatchCategory, TMMatchCountry tMMatchCountry,
			TMMatchSeason tMMatchSeason, String matchName, String matchShortName, String matchCrrtStage) {
		this.matchId = matchId;
		this.tMMatchCategory = tMMatchCategory;
		this.tMMatchCountry = tMMatchCountry;
		this.tMMatchSeason = tMMatchSeason;
		this.matchName = matchName;
		this.matchShortName = matchShortName;
		this.matchCrrtStage = matchCrrtStage;
	}

	public int getMatchId() {
		return this.matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

	public TMMatchCategory getTMMatchCategory() {
		return this.tMMatchCategory;
	}

	public void setTMMatchCategory(TMMatchCategory tMMatchCategory) {
		this.tMMatchCategory = tMMatchCategory;
	}

	public TMMatchCountry getTMMatchCountry() {
		return this.tMMatchCountry;
	}

	public void setTMMatchCountry(TMMatchCountry tMMatchCountry) {
		this.tMMatchCountry = tMMatchCountry;
	}

	public TMMatchSeason getTMMatchSeason() {
		return this.tMMatchSeason;
	}

	public void setTMMatchSeason(TMMatchSeason tMMatchSeason) {
		this.tMMatchSeason = tMMatchSeason;
	}

	public String getMatchName() {
		return this.matchName;
	}

	public void setMatchName(String matchName) {
		this.matchName = matchName;
	}

	public String getMatchShortName() {
		return this.matchShortName;
	}

	public void setMatchShortName(String matchShortName) {
		this.matchShortName = matchShortName;
	}

	public String getMatchCrrtStage() {
		return this.matchCrrtStage;
	}

	public void setMatchCrrtStage(String matchCrrtStage) {
		this.matchCrrtStage = matchCrrtStage;
	}
}
