package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TMBetTgtMatch generated by hbm2java
 */
@Entity
@Table(name="t_m_bet_tgt_match")
public class TMBetTgtMatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1398084954934213006L;
	@Id
	@Column(name="match_id")
	private int matchId;
	
	//TMMatchCategory实体被TMBetTgtMatch实体引用了,该实体中用来关联的属性（外键）为：match_category_id
	@OneToOne
	@JoinColumn(name = "match_category_id")
	private TMMatchCategory tMMatchCategory;
	
	@OneToOne
	@JoinColumn(name = "match_cy_id")
	private TMMatchCountry TMMatchCountry;
	
	@OneToOne
	@JoinColumn(name = "match_ssn_id")
	private TMMatchSeason TMMatchSeason;
	
	@Column(name = "match_name")
	private String matchName;
	
	@Column(name = "match_short_name")
	private String matchShortName;
	
	@Column(name = "match_crrt_stage")
	private String matchCrrtStage;

	public TMBetTgtMatch() {
	}

	public TMBetTgtMatch(int matchId, TMMatchCategory tMMatchCategory, TMMatchCountry TMMatchCountry,
			TMMatchSeason TMMatchSeason, String matchName, String matchShortName, String matchCrrtStage) {
		this.matchId = matchId;
		this.tMMatchCategory = tMMatchCategory;
		this.TMMatchCountry = TMMatchCountry;
		this.TMMatchSeason = TMMatchSeason;
		this.matchName = matchName;
		this.matchShortName = matchShortName;
		this.matchCrrtStage = matchCrrtStage;
	}

	public int getMatchId() {
		return this.matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

	public TMMatchCategory getTMMatchCategory() {
		return this.tMMatchCategory;
	}

	public void setTMMatchCategory(TMMatchCategory tMMatchCategory) {
		this.tMMatchCategory = tMMatchCategory;
	}

	public TMMatchCountry getTMMatchCountry() {
		return this.TMMatchCountry;
	}

	public void setTMMatchCountry(TMMatchCountry TMMatchCountry) {
		this.TMMatchCountry = TMMatchCountry;
	}

	public TMMatchSeason getTMMatchSeason() {
		return this.TMMatchSeason;
	}

	public void setTMMatchSeason(TMMatchSeason TMMatchSeason) {
		this.TMMatchSeason = TMMatchSeason;
	}

	public String getMatchName() {
		return this.matchName;
	}

	public void setMatchName(String matchName) {
		this.matchName = matchName;
	}

	public String getMatchShortName() {
		return this.matchShortName;
	}

	public void setMatchShortName(String matchShortName) {
		this.matchShortName = matchShortName;
	}

	public String getMatchCrrtStage() {
		return this.matchCrrtStage;
	}

	public void setMatchCrrtStage(String matchCrrtStage) {
		this.matchCrrtStage = matchCrrtStage;
	}
}
