package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMBetTgtMatch generated by hbm2java
 */
public class TMBetTgtMatch implements java.io.Serializable {

	private int matchId;
	private TMMatchCategory TMMatchCategory;
	private TMMatchCountry TMMatchCountry;
	private TMMatchSeason TMMatchSeason;
	private String matchName;
	private String matchShortName;
	private String matchCrrtStage;
	private Set TOrderDetails = new HashSet(0);
	private Set TMMatchTeams = new HashSet(0);

	public TMBetTgtMatch() {
	}

	public TMBetTgtMatch(int matchId, TMMatchCategory TMMatchCategory, TMMatchCountry TMMatchCountry,
			TMMatchSeason TMMatchSeason, String matchName, String matchShortName) {
		this.matchId = matchId;
		this.TMMatchCategory = TMMatchCategory;
		this.TMMatchCountry = TMMatchCountry;
		this.TMMatchSeason = TMMatchSeason;
		this.matchName = matchName;
		this.matchShortName = matchShortName;
	}

	public TMBetTgtMatch(int matchId, TMMatchCategory TMMatchCategory, TMMatchCountry TMMatchCountry,
			TMMatchSeason TMMatchSeason, String matchName, String matchShortName, String matchCrrtStage,
			Set TOrderDetails, Set TMMatchTeams) {
		this.matchId = matchId;
		this.TMMatchCategory = TMMatchCategory;
		this.TMMatchCountry = TMMatchCountry;
		this.TMMatchSeason = TMMatchSeason;
		this.matchName = matchName;
		this.matchShortName = matchShortName;
		this.matchCrrtStage = matchCrrtStage;
		this.TOrderDetails = TOrderDetails;
		this.TMMatchTeams = TMMatchTeams;
	}

	public int getMatchId() {
		return this.matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

	public TMMatchCategory getTMMatchCategory() {
		return this.TMMatchCategory;
	}

	public void setTMMatchCategory(TMMatchCategory TMMatchCategory) {
		this.TMMatchCategory = TMMatchCategory;
	}

	public TMMatchCountry getTMMatchCountry() {
		return this.TMMatchCountry;
	}

	public void setTMMatchCountry(TMMatchCountry TMMatchCountry) {
		this.TMMatchCountry = TMMatchCountry;
	}

	public TMMatchSeason getTMMatchSeason() {
		return this.TMMatchSeason;
	}

	public void setTMMatchSeason(TMMatchSeason TMMatchSeason) {
		this.TMMatchSeason = TMMatchSeason;
	}

	public String getMatchName() {
		return this.matchName;
	}

	public void setMatchName(String matchName) {
		this.matchName = matchName;
	}

	public String getMatchShortName() {
		return this.matchShortName;
	}

	public void setMatchShortName(String matchShortName) {
		this.matchShortName = matchShortName;
	}

	public String getMatchCrrtStage() {
		return this.matchCrrtStage;
	}

	public void setMatchCrrtStage(String matchCrrtStage) {
		this.matchCrrtStage = matchCrrtStage;
	}

	public Set getTOrderDetails() {
		return this.TOrderDetails;
	}

	public void setTOrderDetails(Set TOrderDetails) {
		this.TOrderDetails = TOrderDetails;
	}

	public Set getTMMatchTeams() {
		return this.TMMatchTeams;
	}

	public void setTMMatchTeams(Set TMMatchTeams) {
		this.TMMatchTeams = TMMatchTeams;
	}

}
