package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TMEarlyStageBetType generated by hbm2java
 */
@Entity
@Table(name = "t_m_early_stage_bet_type")
public class TMEarlyStageBetType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2278922058446197858L;
	
	@Id
	@Column(name = "bet_type_id")
	private int betTypeId;
	
	@ManyToOne
	@JoinColumn(name = "match_category_id")
	private TMMatchCategory TMMatchCategory;
	
	@Column(name = "bet_type_name")
	private String betTypeName;

	public TMEarlyStageBetType() {
	}

	public TMEarlyStageBetType(int betTypeId, TMMatchCategory TMMatchCategory, String betTypeName) {
		this.betTypeId = betTypeId;
		this.TMMatchCategory = TMMatchCategory;
		this.betTypeName = betTypeName;
	}

	public int getBetTypeId() {
		return this.betTypeId;
	}

	public void setBetTypeId(int betTypeId) {
		this.betTypeId = betTypeId;
	}

	public TMMatchCategory getTMMatchCategory() {
		return this.TMMatchCategory;
	}

	public void setTMMatchCategory(TMMatchCategory TMMatchCategory) {
		this.TMMatchCategory = TMMatchCategory;
	}

	public String getBetTypeName() {
		return this.betTypeName;
	}

	public void setBetTypeName(String betTypeName) {
		this.betTypeName = betTypeName;
	}
}
