package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMEarlyStageBetType generated by hbm2java
 */
public class TMEarlyStageBetType implements java.io.Serializable {

	private int betTypeId;
	private TMMatchCategory TMMatchCategory;
	private String betTypeName;
	private Set TOrderDetails = new HashSet(0);

	public TMEarlyStageBetType() {
	}

	public TMEarlyStageBetType(int betTypeId, TMMatchCategory TMMatchCategory, String betTypeName) {
		this.betTypeId = betTypeId;
		this.TMMatchCategory = TMMatchCategory;
		this.betTypeName = betTypeName;
	}

	public TMEarlyStageBetType(int betTypeId, TMMatchCategory TMMatchCategory, String betTypeName, Set TOrderDetails) {
		this.betTypeId = betTypeId;
		this.TMMatchCategory = TMMatchCategory;
		this.betTypeName = betTypeName;
		this.TOrderDetails = TOrderDetails;
	}

	public int getBetTypeId() {
		return this.betTypeId;
	}

	public void setBetTypeId(int betTypeId) {
		this.betTypeId = betTypeId;
	}

	public TMMatchCategory getTMMatchCategory() {
		return this.TMMatchCategory;
	}

	public void setTMMatchCategory(TMMatchCategory TMMatchCategory) {
		this.TMMatchCategory = TMMatchCategory;
	}

	public String getBetTypeName() {
		return this.betTypeName;
	}

	public void setBetTypeName(String betTypeName) {
		this.betTypeName = betTypeName;
	}

	public Set getTOrderDetails() {
		return this.TOrderDetails;
	}

	public void setTOrderDetails(Set TOrderDetails) {
		this.TOrderDetails = TOrderDetails;
	}

}
