package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TMGlobalMatch generated by hbm2java
 */
@Entity
@Table(name = "t_m_global_match")
public class TMGlobalMatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6081919832154556944L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="gbl_match_name")
	private String gblMatchName;

	public TMGlobalMatch() {
	}

	public TMGlobalMatch(int id, String gblMatchName) {
		this.id = id;
		this.gblMatchName = gblMatchName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGblMatchName() {
		return this.gblMatchName;
	}

	public void setGblMatchName(String gblMatchName) {
		this.gblMatchName = gblMatchName;
	}

}
