package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMMatchCategory generated by hbm2java
 */
public class TMMatchCategory implements java.io.Serializable {

	private int matchCategoryId;
	private String matchCategoryName;
	private Set TMBetTgtMatches = new HashSet(0);
	private Set TMEarlyStageBetTypes = new HashSet(0);

	public TMMatchCategory() {
	}

	public TMMatchCategory(int matchCategoryId, String matchCategoryName) {
		this.matchCategoryId = matchCategoryId;
		this.matchCategoryName = matchCategoryName;
	}

	public TMMatchCategory(int matchCategoryId, String matchCategoryName, Set TMBetTgtMatches,
			Set TMEarlyStageBetTypes) {
		this.matchCategoryId = matchCategoryId;
		this.matchCategoryName = matchCategoryName;
		this.TMBetTgtMatches = TMBetTgtMatches;
		this.TMEarlyStageBetTypes = TMEarlyStageBetTypes;
	}

	public int getMatchCategoryId() {
		return this.matchCategoryId;
	}

	public void setMatchCategoryId(int matchCategoryId) {
		this.matchCategoryId = matchCategoryId;
	}

	public String getMatchCategoryName() {
		return this.matchCategoryName;
	}

	public void setMatchCategoryName(String matchCategoryName) {
		this.matchCategoryName = matchCategoryName;
	}

	public Set getTMBetTgtMatches() {
		return this.TMBetTgtMatches;
	}

	public void setTMBetTgtMatches(Set TMBetTgtMatches) {
		this.TMBetTgtMatches = TMBetTgtMatches;
	}

	public Set getTMEarlyStageBetTypes() {
		return this.TMEarlyStageBetTypes;
	}

	public void setTMEarlyStageBetTypes(Set TMEarlyStageBetTypes) {
		this.TMEarlyStageBetTypes = TMEarlyStageBetTypes;
	}

}
