package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

/**
 * TMMatchTeamId generated by hbm2java
 */
public class TMMatchTeamId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9179827386526669284L;
	private int teamId;
	private int matchId;

	public TMMatchTeamId() {
	}

	public TMMatchTeamId(int teamId, int matchId) {
		this.teamId = teamId;
		this.matchId = matchId;
	}

	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	public int getMatchId() {
		return this.matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMMatchTeamId))
			return false;
		TMMatchTeamId castOther = (TMMatchTeamId) other;

		return (this.getTeamId() == castOther.getTeamId()) && (this.getMatchId() == castOther.getMatchId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeamId();
		result = 37 * result + this.getMatchId();
		return result;
	}

}
