package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMMatchCountry generated by hbm2java
 */
public class TMMatchCountry implements java.io.Serializable {

	private int matchCyId;
	private TMGlobalMatch TMGlobalMatch;
	private String matchCyName;
	private int cyShowOrder;
	private Set TMBetTgtMatches = new HashSet(0);

	public TMMatchCountry() {
	}

	public TMMatchCountry(int matchCyId, TMGlobalMatch TMGlobalMatch, String matchCyName, int cyShowOrder) {
		this.matchCyId = matchCyId;
		this.TMGlobalMatch = TMGlobalMatch;
		this.matchCyName = matchCyName;
		this.cyShowOrder = cyShowOrder;
	}

	public TMMatchCountry(int matchCyId, TMGlobalMatch TMGlobalMatch, String matchCyName, int cyShowOrder,
			Set TMBetTgtMatches) {
		this.matchCyId = matchCyId;
		this.TMGlobalMatch = TMGlobalMatch;
		this.matchCyName = matchCyName;
		this.cyShowOrder = cyShowOrder;
		this.TMBetTgtMatches = TMBetTgtMatches;
	}

	public int getMatchCyId() {
		return this.matchCyId;
	}

	public void setMatchCyId(int matchCyId) {
		this.matchCyId = matchCyId;
	}

	public TMGlobalMatch getTMGlobalMatch() {
		return this.TMGlobalMatch;
	}

	public void setTMGlobalMatch(TMGlobalMatch TMGlobalMatch) {
		this.TMGlobalMatch = TMGlobalMatch;
	}

	public String getMatchCyName() {
		return this.matchCyName;
	}

	public void setMatchCyName(String matchCyName) {
		this.matchCyName = matchCyName;
	}

	public int getCyShowOrder() {
		return this.cyShowOrder;
	}

	public void setCyShowOrder(int cyShowOrder) {
		this.cyShowOrder = cyShowOrder;
	}

	public Set getTMBetTgtMatches() {
		return this.TMBetTgtMatches;
	}

	public void setTMBetTgtMatches(Set TMBetTgtMatches) {
		this.TMBetTgtMatches = TMBetTgtMatches;
	}

}
