package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMMatchSeason generated by hbm2java
 */
public class TMMatchSeason implements java.io.Serializable {

	private int matchSsnId;
	private String matchSsnName;
	private Set TMBetTgtMatches = new HashSet(0);
	private Set TMMatchTeams = new HashSet(0);
	private Set TOrderDetails = new HashSet(0);

	public TMMatchSeason() {
	}

	public TMMatchSeason(int matchSsnId, String matchSsnName) {
		this.matchSsnId = matchSsnId;
		this.matchSsnName = matchSsnName;
	}

	public TMMatchSeason(int matchSsnId, String matchSsnName, Set TMBetTgtMatches, Set TMMatchTeams,
			Set TOrderDetails) {
		this.matchSsnId = matchSsnId;
		this.matchSsnName = matchSsnName;
		this.TMBetTgtMatches = TMBetTgtMatches;
		this.TMMatchTeams = TMMatchTeams;
		this.TOrderDetails = TOrderDetails;
	}

	public int getMatchSsnId() {
		return this.matchSsnId;
	}

	public void setMatchSsnId(int matchSsnId) {
		this.matchSsnId = matchSsnId;
	}

	public String getMatchSsnName() {
		return this.matchSsnName;
	}

	public void setMatchSsnName(String matchSsnName) {
		this.matchSsnName = matchSsnName;
	}

	public Set getTMBetTgtMatches() {
		return this.TMBetTgtMatches;
	}

	public void setTMBetTgtMatches(Set TMBetTgtMatches) {
		this.TMBetTgtMatches = TMBetTgtMatches;
	}

	public Set getTMMatchTeams() {
		return this.TMMatchTeams;
	}

	public void setTMMatchTeams(Set TMMatchTeams) {
		this.TMMatchTeams = TMMatchTeams;
	}

	public Set getTOrderDetails() {
		return this.TOrderDetails;
	}

	public void setTOrderDetails(Set TOrderDetails) {
		this.TOrderDetails = TOrderDetails;
	}

}
