package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TMMatchCategory generated by hbm2java
 */
@Entity
@Table(name = "t_m_match_category")
public class TMMatchCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8186890856201607895L;
	
	@Id
	@Column(name = "match_category_id")
	private int matchCategoryId;
	
	@Column(name = "match_category_name")
	private String matchCategoryName;

	public TMMatchCategory() {
	}

	public TMMatchCategory(int matchCategoryId, String matchCategoryName) {
		this.matchCategoryId = matchCategoryId;
		this.matchCategoryName = matchCategoryName;
	}

	public int getMatchCategoryId() {
		return this.matchCategoryId;
	}

	public void setMatchCategoryId(int matchCategoryId) {
		this.matchCategoryId = matchCategoryId;
	}

	public String getMatchCategoryName() {
		return this.matchCategoryName;
	}

	public void setMatchCategoryName(String matchCategoryName) {
		this.matchCategoryName = matchCategoryName;
	}
}
