package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TMMatchSeason generated by hbm2java
 */
@Entity
@Table(name = "t_m_match_season")
public class TMMatchSeason implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1262869515526060068L;
	
	@Id
	@Column(name = "match_ssn_id")
	private int matchSsnId;
	
	@Column(name = "match_ssn_name")
	private String matchSsnName;

	public TMMatchSeason() {
	}

	public TMMatchSeason(int matchSsnId) {
		super();
		this.matchSsnId = matchSsnId;
	}

	public TMMatchSeason(int matchSsnId, String matchSsnName) {
		this.matchSsnId = matchSsnId;
		this.matchSsnName = matchSsnName;
	}

	public int getMatchSsnId() {
		return this.matchSsnId;
	}

	public void setMatchSsnId(int matchSsnId) {
		this.matchSsnId = matchSsnId;
	}

	public String getMatchSsnName() {
		return this.matchSsnName;
	}

	public void setMatchSsnName(String matchSsnName) {
		this.matchSsnName = matchSsnName;
	}
}
