package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TMMatchTeam generated by hbm2java
 */
public class TMMatchTeam implements java.io.Serializable {

	private TMMatchTeamId id;
	private TMBetTgtMatch TMBetTgtMatch;
	private TMMatchSeason TMMatchSeason;
	private String teamName;
	private String teamShortName;
	private String matchGroup;
	private String knktMatchRival;
	private String teamStanding;
	private Set TOrderDetails = new HashSet(0);

	public TMMatchTeam() {
	}

	public TMMatchTeam(TMMatchTeamId id, TMBetTgtMatch TMBetTgtMatch, TMMatchSeason TMMatchSeason, String teamName,
			String teamShortName) {
		this.id = id;
		this.TMBetTgtMatch = TMBetTgtMatch;
		this.TMMatchSeason = TMMatchSeason;
		this.teamName = teamName;
		this.teamShortName = teamShortName;
	}

	public TMMatchTeam(TMMatchTeamId id, TMBetTgtMatch TMBetTgtMatch, TMMatchSeason TMMatchSeason, String teamName,
			String teamShortName, String matchGroup, String knktMatchRival, String teamStanding, Set TOrderDetails) {
		this.id = id;
		this.TMBetTgtMatch = TMBetTgtMatch;
		this.TMMatchSeason = TMMatchSeason;
		this.teamName = teamName;
		this.teamShortName = teamShortName;
		this.matchGroup = matchGroup;
		this.knktMatchRival = knktMatchRival;
		this.teamStanding = teamStanding;
		this.TOrderDetails = TOrderDetails;
	}

	public TMMatchTeamId getId() {
		return this.id;
	}

	public void setId(TMMatchTeamId id) {
		this.id = id;
	}

	public TMBetTgtMatch getTMBetTgtMatch() {
		return this.TMBetTgtMatch;
	}

	public void setTMBetTgtMatch(TMBetTgtMatch TMBetTgtMatch) {
		this.TMBetTgtMatch = TMBetTgtMatch;
	}

	public TMMatchSeason getTMMatchSeason() {
		return this.TMMatchSeason;
	}

	public void setTMMatchSeason(TMMatchSeason TMMatchSeason) {
		this.TMMatchSeason = TMMatchSeason;
	}

	public String getTeamName() {
		return this.teamName;
	}

	public void setTeamName(String teamName) {
		this.teamName = teamName;
	}

	public String getTeamShortName() {
		return this.teamShortName;
	}

	public void setTeamShortName(String teamShortName) {
		this.teamShortName = teamShortName;
	}

	public String getMatchGroup() {
		return this.matchGroup;
	}

	public void setMatchGroup(String matchGroup) {
		this.matchGroup = matchGroup;
	}

	public String getKnktMatchRival() {
		return this.knktMatchRival;
	}

	public void setKnktMatchRival(String knktMatchRival) {
		this.knktMatchRival = knktMatchRival;
	}

	public String getTeamStanding() {
		return this.teamStanding;
	}

	public void setTeamStanding(String teamStanding) {
		this.teamStanding = teamStanding;
	}

	public Set getTOrderDetails() {
		return this.TOrderDetails;
	}

	public void setTOrderDetails(Set TOrderDetails) {
		this.TOrderDetails = TOrderDetails;
	}

}
