package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

/**
 * TMMatchTeamId generated by hbm2java
 */
public class TMMatchTeamId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9179827386526669284L;
	private int team_id;
	private int match_id;

	public TMMatchTeamId() {
	}

	public TMMatchTeamId(int team_id, int match_id) {
		this.team_id = team_id;
		this.match_id = match_id;
	}

	public int getTeam_id() {
		return team_id;
	}

	public void setTeam_id(int team_id) {
		this.team_id = team_id;
	}

	public int getMatch_id() {
		return match_id;
	}

	public void setMatch_id(int match_id) {
		this.match_id = match_id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TMMatchTeamId))
			return false;
		TMMatchTeamId castOther = (TMMatchTeamId) other;

		return (this.getTeam_id() == castOther.getTeam_id()) && (this.getMatch_id() == castOther.getMatch_id());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeam_id();
		result = 37 * result + this.getMatch_id();
		return result;
	}

}
