package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TMMatchCountry generated by hbm2java
 */
@Entity
@Table(name = "t_m_match_country")
public class TMMatchCountry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8323576681007671704L;
	
	@Id
	@Column(name = "match_cy_id")
	private int matchCyId;
	
	@ManyToOne
	@JoinColumn(name = "id")
	private TMGlobalMatch TMGlobalMatch;
	
	@Column(name = "match_cy_name")
	private String matchCyName;
	
	@Column(name = "cy_show_order")
	private int cyShowOrder;

	public TMMatchCountry() {
	}

	public TMMatchCountry(int matchCyId, TMGlobalMatch TMGlobalMatch, String matchCyName, int cyShowOrder) {
		this.matchCyId = matchCyId;
		this.TMGlobalMatch = TMGlobalMatch;
		this.matchCyName = matchCyName;
		this.cyShowOrder = cyShowOrder;
	}

	public int getMatchCyId() {
		return this.matchCyId;
	}

	public void setMatchCyId(int matchCyId) {
		this.matchCyId = matchCyId;
	}

	public TMGlobalMatch getTMGlobalMatch() {
		return this.TMGlobalMatch;
	}

	public void setTMGlobalMatch(TMGlobalMatch TMGlobalMatch) {
		this.TMGlobalMatch = TMGlobalMatch;
	}

	public String getMatchCyName() {
		return this.matchCyName;
	}

	public void setMatchCyName(String matchCyName) {
		this.matchCyName = matchCyName;
	}

	public int getCyShowOrder() {
		return this.cyShowOrder;
	}

	public void setCyShowOrder(int cyShowOrder) {
		this.cyShowOrder = cyShowOrder;
	}
}
