package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * TOrder generated by hbm2java
 */
public class TOrder implements java.io.Serializable {

	private Integer orderId;
	private Double orderPrpl;
	private String betTgtMatches;
	private Double estmBonus;
	private Byte isWin;
	private Byte isClosed;
	private Byte isClosedManually;
	private Date orderDate;

	public TOrder() {
	}

	public TOrder(Date orderDate) {
		this.orderDate = orderDate;
	}

	public TOrder(Double orderPrpl, String betTgtMatches, Double estmBonus, Byte isWin, Byte isClosed,
			Byte isClosedManually, Date orderDate) {
		this.orderPrpl = orderPrpl;
		this.betTgtMatches = betTgtMatches;
		this.estmBonus = estmBonus;
		this.isWin = isWin;
		this.isClosed = isClosed;
		this.isClosedManually = isClosedManually;
		this.orderDate = orderDate;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Double getOrderPrpl() {
		return this.orderPrpl;
	}

	public void setOrderPrpl(Double orderPrpl) {
		this.orderPrpl = orderPrpl;
	}

	public String getBetTgtMatches() {
		return this.betTgtMatches;
	}

	public void setBetTgtMatches(String betTgtMatches) {
		this.betTgtMatches = betTgtMatches;
	}

	public Double getEstmBonus() {
		return this.estmBonus;
	}

	public void setEstmBonus(Double estmBonus) {
		this.estmBonus = estmBonus;
	}

	public Byte getIsWin() {
		return this.isWin;
	}

	public void setIsWin(Byte isWin) {
		this.isWin = isWin;
	}

	public Byte getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Byte isClosed) {
		this.isClosed = isClosed;
	}

	public Byte getIsClosedManually() {
		return this.isClosedManually;
	}

	public void setIsClosedManually(Byte isClosedManually) {
		this.isClosedManually = isClosedManually;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
