package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

/**
 * TOrderDetail generated by hbm2java
 */
public class TOrderDetail implements java.io.Serializable {

	private TOrderDetailId id;
	private TMBetTgtMatch TMBetTgtMatch;
	private TMEarlyStageBetType TMEarlyStageBetType;
	private TMMatchSeason TMMatchSeason;
	private TMMatchTeam TMMatchTeam;
	private double returnRate;
	private Byte isClosed;

	public TOrderDetail() {
	}

	public TOrderDetail(TOrderDetailId id, TMBetTgtMatch TMBetTgtMatch, TMEarlyStageBetType TMEarlyStageBetType,
			TMMatchSeason TMMatchSeason, TMMatchTeam TMMatchTeam, double returnRate) {
		this.id = id;
		this.TMBetTgtMatch = TMBetTgtMatch;
		this.TMEarlyStageBetType = TMEarlyStageBetType;
		this.TMMatchSeason = TMMatchSeason;
		this.TMMatchTeam = TMMatchTeam;
		this.returnRate = returnRate;
	}

	public TOrderDetail(TOrderDetailId id, TMBetTgtMatch TMBetTgtMatch, TMEarlyStageBetType TMEarlyStageBetType,
			TMMatchSeason TMMatchSeason, TMMatchTeam TMMatchTeam, double returnRate, Byte isClosed) {
		this.id = id;
		this.TMBetTgtMatch = TMBetTgtMatch;
		this.TMEarlyStageBetType = TMEarlyStageBetType;
		this.TMMatchSeason = TMMatchSeason;
		this.TMMatchTeam = TMMatchTeam;
		this.returnRate = returnRate;
		this.isClosed = isClosed;
	}

	public TOrderDetailId getId() {
		return this.id;
	}

	public void setId(TOrderDetailId id) {
		this.id = id;
	}

	public TMBetTgtMatch getTMBetTgtMatch() {
		return this.TMBetTgtMatch;
	}

	public void setTMBetTgtMatch(TMBetTgtMatch TMBetTgtMatch) {
		this.TMBetTgtMatch = TMBetTgtMatch;
	}

	public TMEarlyStageBetType getTMEarlyStageBetType() {
		return this.TMEarlyStageBetType;
	}

	public void setTMEarlyStageBetType(TMEarlyStageBetType TMEarlyStageBetType) {
		this.TMEarlyStageBetType = TMEarlyStageBetType;
	}

	public TMMatchSeason getTMMatchSeason() {
		return this.TMMatchSeason;
	}

	public void setTMMatchSeason(TMMatchSeason TMMatchSeason) {
		this.TMMatchSeason = TMMatchSeason;
	}

	public TMMatchTeam getTMMatchTeam() {
		return this.TMMatchTeam;
	}

	public void setTMMatchTeam(TMMatchTeam TMMatchTeam) {
		this.TMMatchTeam = TMMatchTeam;
	}

	public double getReturnRate() {
		return this.returnRate;
	}

	public void setReturnRate(double returnRate) {
		this.returnRate = returnRate;
	}

	public Byte getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Byte isClosed) {
		this.isClosed = isClosed;
	}

}
