package com.hpe.kevin.business.entities;
// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TOrder generated by hbm2java
 */
@Entity
@Table(name = "t_order")
public class TOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6712854053684544350L;
	
	@Id
	@Column(name = "order_id")
	private Integer orderId;
	
	@Column(name = "order_prpl")
	private Double orderPrpl;
	
	@Column(name = "bet_tgt_matches")
	private String betTgtMatches;
	
	@Column(name = "estm_bonus")
	private Double estmBonus;
	
	@Column(name = "is_win")
	private Byte isWin;
	
	@Column(name = "is_closed")
	private Byte isClosed;
	
	@Column(name = "is_closed_manually")
	private Byte isClosedManually;
	
	@Column(name = "order_date")
	private Date orderDate;
	
	@OneToOne
	@JoinColumn(name="user_id")
	private TUser user;
	
	@OneToMany
	@JoinColumn(name="order_id", insertable = false, updatable = false)
	private List<TOrderDetail> orderDetailList = new ArrayList<TOrderDetail>();

	public TOrder() {
	}

	public TOrder(Integer orderId, Double orderPrpl, String betTgtMatches, Double estmBonus, Byte isWin, Byte isClosed,
			Byte isClosedManually, Date orderDate, TUser user, List<TOrderDetail> orderDetailList) {
		super();
		this.orderId = orderId;
		this.orderPrpl = orderPrpl;
		this.betTgtMatches = betTgtMatches;
		this.estmBonus = estmBonus;
		this.isWin = isWin;
		this.isClosed = isClosed;
		this.isClosedManually = isClosedManually;
		this.orderDate = orderDate;
		this.user = user;
		this.orderDetailList = orderDetailList;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Double getOrderPrpl() {
		return this.orderPrpl;
	}

	public void setOrderPrpl(Double orderPrpl) {
		this.orderPrpl = orderPrpl;
	}

	public String getBetTgtMatches() {
		return this.betTgtMatches;
	}

	public void setBetTgtMatches(String betTgtMatches) {
		this.betTgtMatches = betTgtMatches;
	}

	public Double getEstmBonus() {
		return this.estmBonus;
	}

	public void setEstmBonus(Double estmBonus) {
		this.estmBonus = estmBonus;
	}

	public Byte getIsWin() {
		return this.isWin;
	}

	public void setIsWin(Byte isWin) {
		this.isWin = isWin;
	}

	public Byte getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Byte isClosed) {
		this.isClosed = isClosed;
	}

	public Byte getIsClosedManually() {
		return this.isClosedManually;
	}

	public void setIsClosedManually(Byte isClosedManually) {
		this.isClosedManually = isClosedManually;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public List<TOrderDetail> getOrderDetailList() {
		return orderDetailList;
	}

	public void setOrderDetailList(List<TOrderDetail> orderDetailList) {
		this.orderDetailList = orderDetailList;
	}
	
	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}
}
