package com.hpe.kevin.business.entities;

import javax.persistence.Column;

// Generated 2017/12/20 14:07:38 by Hibernate Tools 5.2.3.Final

/**
 * TOrderDetailId generated by hbm2java
 */
public class TOrderDetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1876458507538719596L;
	@Column(name = "order_id")
	private int orderId;
	@Column(name = "order_detail_id")
	private int orderDetailId;

	public TOrderDetailId() {
	}

	public TOrderDetailId(int orderId, int orderDetailId) {
		this.orderId = orderId;
		this.orderDetailId = orderDetailId;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public int getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(int orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TOrderDetailId))
			return false;
		TOrderDetailId castOther = (TOrderDetailId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getOrderDetailId() == castOther.getOrderDetailId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getOrderDetailId();
		return result;
	}

}
